//------------------------------------------------------------------------
// Copyright(c) 2024 .
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"VST3-Test-SteinbergGUI.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"VST3-Test-SteinbergGUI VST3 (64Bit)"
#else
#define stringFileDescription	"VST3-Test-SteinbergGUI VST3"
#endif
#define stringCompanyName		"\0"
#define stringLegalCopyright	"Copyright(c) 2024 ."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
